@api = http://localhost:4000/api

################################################
POST http://localhost:4000/api/login HTTP/1.1
Content-type: application/json
                                           
{
    "usuario": "anderk333",
    "password": "0981942117tanki"
}

#################################################
POST {{api}}/register HTTP/1.1
Content-type: application/json                                                

{
    "usuario": "anderk333",
    "password": "0981942117tanki"
}

##################################################
POST {{api}}/agregar_nota HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQsIm5hbWUiOiJhbmRlcmszMzMiLCJpYXQiOjE2NDAzMjU1MDJ9.uDgcvqc7GXpx5fDwdDFN389ik9utxs9Ac1yu2q3Vuew

{
    "titulo":"Deber de base de datos",
    "cuerpo":"Hacer una consulta con inner join",
    "import":"2"
}

##################################################
DELETE  {{api}}/deleteNote/4 HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkFuZGVyc29uIiwiaWF0IjoxNjM2OTQ4NDEyfQ.G9zxFkK-Z9vMBalHt0MZ8z_jy7pPVxDPv5gIA1HfDAU


##################################################
PUT {{api}}/editNote/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsIm5hbWUiOiJhbmRlcmsyMjIiLCJpYXQiOjE2Mzk2MzQxODB9.B9WEP8Ee8qIEigxpLWzrrn_RwA60LmuMz0KykzXyCkU

{
    "titulo":"Deber calculo lineal",
    "cuerpo":"Como sacar el limite de una lineas",
    "import":"2"
}

                                             
##################################################
GET  {{api}}/ver_nota/4 HTTP/1.1
Content-Type: application/x-www-form-urlencoded;
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsIm5hbWUiOiJhbmRlcmsyMjIiLCJpYXQiOjE2NDAzMjQ4Mjh9.PF5SPRRsDfk3oV9ZLYOeAMgwIUE0q9ncgLv5er7SkAk

#################################################
GET {{api}}/users HTTP/1.1
Content-type: application/json

#################################################
GET {{api}}/getNotes HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjcsIm5hbWUiOiJBbmRlcnNvbiIsImlhdCI6MTY0MDMyNzQxOCwiZXhwIjoxNjQwNjczMDE4fQ.rLgMtvbVPA_ryRcIKDhdCpo-APBC3CEdM-7twHQr4ko